version: '3.9'

services:
  # Django web application service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CAB432-web
    ports:
      - "8000:8000"
    command: ["/code/entrypoint.sh"]
    environment:
      # Database configuration
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}

      # Ollama AI service URL
      OLLAMA_URL: "http://ollama:11434"

    # Mount project code
    volumes:
      - .:/code
