version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CAB432-web
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
      USE_S3: "True"
      AWS_PROFILE: "CAB432-STUDENT"
      AWS_REGION: "ap-southeast-2"
      AWS_STORAGE_BUCKET_NAME: "justinsinghatwalbucket"
      OLLAMA_URL: "http://ollama:11434"
      COGNITO_USER_POOL_ID: "ap-southeast-2_XEtlj9zEG"
      COGNITO_CLIENT_ID: "5dmsjn9reflk2l2auq48qr9r1r"
      COGNITO_CLIENT_SECRET: "vfor73vf1774pq8eqmgrr3j87d44o160psmpvep0l34s19fndpt"
      COGNITO_REGION: "ap-southeast-2"
      CACHE_HOST: "n11605618-ollama-memcached.km2jzi.cfg.apse2.cache.amazonaws.com"
      CACHE_PORT: "11211"
    volumes:
      - ./code:/code
      - /home/ubuntu/.aws:/root/.aws:ro
