version: '3.9'

services:
  # Local MariaDB
  db:
    image: mariadb:11
    container_name: CAB432-db
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Ollama service
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: cab432-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "ollama serve &
             until curl -s http://localhost:11434/api/tags >/dev/null; do sleep 2; done &&
             ollama pull mistral &&
             wait"

  # Django web service
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CAB432-web
    command: >
      sh -c "python db.py &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000 & 
             until curl -s http://localhost:8000 >/dev/null; do sleep 2; done &&
             python load_test.py > /code/load_test.log 2>&1"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - ollama
      - minio

  # MinIO service
  minio:
    image: minio/minio:latest
    container_name: cab432-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  db_data:
  ollama_data:
  minio_data:
