version: '3.9'

services:
  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: cab432-ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: >
      sh -c "ollama serve &
             until curl -s http://localhost:11434/api/tags >/dev/null; do sleep 2; done &&
             ollama pull mistral &&
             wait"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 5s
      retries: 12

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CAB432-web
    depends_on:
      ollama:
        condition: service_healthy
    ports:
      - "8000:8000"
    command: ["/code/entrypoint.sh"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_SSLMODE: ${DB_SSLMODE}
      USE_S3: "True"
      AWS_PROFILE: "CAB432-STUDENT"
      AWS_REGION: "ap-southeast-2"
      AWS_STORAGE_BUCKET_NAME: "justinsinghatwalbucket"
    volumes:
      - .:/code
      - C:\Users\Justin\.aws:/root/.aws:ro

volumes:
  ollama_data:
