# Generated by Django 5.1.7 on 2025-09-20 16:42

import app1.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s3_file_path', models.URLField(
                    max_length=1024,
                    blank=True,
                    null=True,
                    help_text='Full S3 URL of the resume uploaded'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('tailored_resume_s3_url', models.URLField(
                    max_length=1024,
                    blank=True,
                    null=True,
                    help_text='S3 URL of tailored resume'
                )),
                ('score', models.FloatField(blank=True, null=True)),
                ('ai_model', models.CharField(
                    max_length=50,
                    default='mistral',
                    help_text='The Ollama model used'
                )),
                ('status', models.CharField(
                    max_length=20,
                    choices=[
                        ('pending', 'Pending'),
                        ('processing', 'Processing'),
                        ('completed', 'Completed'),
                        ('failed', 'Failed')
                    ],
                    default='pending'
                )),
                ('error_message', models.TextField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('feedback_s3_url', models.URLField(
                    max_length=1024,
                    blank=True,
                    null=True,
                    help_text='Full S3 URL of feedback'
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.resume')),
            ],
        ),
    ]
