# Generated by Django 5.1.7 on 2025-08-25 13:48

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_jobapplication_resume_delete_classtargets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='tailored_resume_file',
            field=models.FileField(blank=True, null=True, upload_to=app1.models.tailored_resume_upload_path),
        ),
        migrations.AlterField(
            model_name='resume',
            name='original_file',
            field=models.FileField(upload_to=app1.models.original_resume_upload_path),
        ),
    ]
