# Generated by Django 5.1.7 on 2025-08-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_jobapplication_tailored_resume_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='ai_model',
            field=models.CharField(default='mistral', help_text='The Ollama model used', max_length=50),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
