# Generated by Django 5.1.7 on 2025-08-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_jobapplication_ai_model_jobapplication_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
