# Generated by Django 5.1.7 on 2025-08-30 17:02

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_jobapplication_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_file',
            field=models.FileField(blank=True, null=True, upload_to=app1.models.feedback_upload_path),
        ),
    ]
