# Generated by Django 5.1.7 on 2025-09-21 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_jobapplication_feedback_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='feedback_file',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='tailored_resume_file',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='original_file',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='feedback_s3_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='tailored_resume_s3_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='s3_file_path',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='ai_model',
            field=models.CharField(default='mistral', max_length=50),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
